### ISSUE TITLE
Reopening the dialog quickly does not work

### ISSUE THREAD

**Issue by paumove** [varunjohn/iOSDialogs4Android#2]
Hello! first... thanks for your work. This dialog is very cool.

I am having a problem trying to open the dialog a second time in a very short period of time. 

My program performs some checks, if it gives an error it shows the dialog with various options. One of these options is "Retry". If I click on this option, it will perfom the same checking as before and if there is an error it will display the dialog again. In this situation, sometimes it works correctly but sometimes it doesn't. Perhaps it is related to the time it takes to perform the checks.

I put a code example in kotlin. It is not literally like my program (mine does the checks on a thread and works with MVVM) but doing so doesn't work either.

```
private fun test() {
        IOSDialog.Builder(context!!)
                .message("Test message")
                .positiveButtonText("Ok")
                .positiveClickListener { dialog ->
                    dialog.dismiss()
                    test()
                }
                .build()
                .show()
    }
```

If I call test() first time is shown, but when I press "Ok" the second time is not shown.

The logcat says:

> 2020-03-19 10:49:48.246 2859-4481/? I/ActivityManager: START u0 {cmp=com.../com.varunjohn1990.iosdialogs4android.IOSDialogView} from uid 10066 on display 0
> 2020-03-19 10:49:48.694 2859-3255/? I/ActivityManager: Displayed com.../com.varunjohn1990.iosdialogs4android.IOSDialogView: +351ms (total +555ms)
> ....
> 2020-03-19 10:49:52.349 2859-4461/? I/ActivityManager: START u0 {cmp=com.***/com.varunjohn1990.iosdialogs4android.IOSDialogView} from uid 10066 on display 0

I think is something with the method starting the activity on IOSDialogView.open. Maybe putting some flags in the Intent can solve it.

Thanks in advance.

**Comment by varunjohn** [comment]
Thanks for raising the issue in detail, it was very helpful..
Well i have fixed in 2.0.1 version.. 
You can use :
''com.varunjohn1990.libraries:iosdialogs4android:2.0.1'
